query ChildCategoriesBySlug(
  $id: ID = "dGVybToxNg=="
  $language: LanguageCodeEnum = FA
) {
  category(id: $id, idType: ID) {
    id
    children(first: 10) {
      edges {
        node {
          id
          name
          description
          cat_cf {
            image {
              id
              sourceUrl
            }
          }
        }
      }
    }
    translation(language: $language) {
      id
    }
  }
}
